//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVBuff.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVBuff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icons {
            get {
                object obj = ResourceManager.GetObject("icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   10100,0,0
        ///10101,24,0
        ///10150,48,0
        ///10151,72,0
        ///10152,96,0
        ///10153,120,0
        ///10154,144,0
        ///10155,168,0
        ///10156,192,0
        ///10157,216,0
        ///10158,240,0
        ///10200,264,0
        ///10201,288,0
        ///10202,312,0
        ///10203,336,0
        ///10204,360,0
        ///10205,384,0
        ///10206,408,0
        ///10207,432,0
        ///10208,456,0
        ///10209,480,0
        ///10210,504,0
        ///10211,528,0
        ///10212,552,0
        ///10213,576,0
        ///10214,600,0
        ///10215,624,0
        ///10216,648,0
        ///10217,672,0
        ///10218,696,0
        ///10250,720,0
        ///10251,744,0
        ///10252,768,0
        ///10253,792,0
        ///10254,816,0
        ///10255,840,0
        ///10256,864,0
        ///10257,888,0
        ///10258,912,0
        ///10259,936,0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string icons_pos {
            get {
                return ResourceManager.GetString("icons_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index,0 [0x0][0x0],1 [0x0][0x4],2 [0x5][0x8],3 [0x3][0xc],4 [0x3][0xd],5 [0x3][0xe],6 [0x3][0xf],7 [0x19][0x14],8 [0x1a][0x14],9 [0x1b][0x14],10 [0x1c][0x14],11 [0x1d][0x14],12 [0x1e][0x14],13 [0x1f][0x14],14 [0x20][0x14],15 [0x3][0x10],16 [0x3][0x11],17 [0x19][0x15],18 [0x5][0xa],19 [0x1a][0x15],20 [0x1b][0x15],21 [0x3][0x12],22 [0x3][0x13]
        ///0,&quot;&quot;,&quot;&quot;,0,0,0,0,0,false,false,false,false,false,false,false,false,0,0,false,0,false,false,0,0
        ///1,&quot;석화&quot;,&quot;손발이 석화되어 행동이 불가능한 상태.&quot;,15001,0,2,6,122,true,false,true,false,fal[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string status_exh_ko {
            get {
                return ResourceManager.GetString("status_exh_ko", resourceCulture);
            }
        }
    }
}
